[package]
name = "skia-canvas"
version = "0.9.30"
description = "A canvas environment for Node"
authors = ["Christian Swinehart <drafting@samizdat.co>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
crc = "^3.0"
css-color = "^0.2"
lazy_static = "1.4.0"
rayon = "^1.5"
ash = "0.35"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6", "promise-api", "task-api"]

[dependencies.skia-safe]
version = "0.50.0"
features = ["textlayout", "gl", "vulkan"]

[target.'cfg(target_os = "macos")'.dependencies]
surfman = "0.4.3"
gl = "0.14.0"
