[package]
name = "skia-canvas"
version = "0.9.30"
description = "A canvas environment for Node"
authors = ["Christian Swinehart <drafting@samizdat.co>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
crc = "^3.0"
css-color = "^0.2"
lazy_static = "1.4.0"
rayon = "^1.5"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6", "promise-api", "task-api"]

[target.'cfg(not(target_os = "macos"))'.dependencies]
skia-safe = { version = "0.50.0", features = ["textlayout", "vulkan"] }
ash = "0.35"

[target.'cfg(target_os = "macos")'.dependencies]
skia-safe = { version = "0.50.0", features = ["textlayout", "metal"] }
metal-rs = { package = "metal", version = "0.24.0" }
foreign-types-shared = "0.1.1"