[package]
name = "skia-canvas"
version = "0.9.31"
description = "A canvas environment for Node"
authors = ["Christian Swinehart <drafting@samizdat.co>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
crc = "^2.1"
css-color = "^0.2"
lazy_static = "1.4.0"
rayon = "^1.5"
surfman = "0.4.3"
gl = "0.14.0"
ash = "0.35"

[dependencies.neon]
version = "0.9.1"
default-features = false
features = ["napi-6", "channel-api"]

[dependencies.skia-safe]
version = "0.46.0"
features = ["textlayout", "gl", "vulkan"]
