name: Apple Silicon

on:
  workflow_dispatch:
    
jobs:
  cross-compile:
    runs-on: macos-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Use Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        target: aarch64-apple-darwin

    - name: Inspect xcode paths
      run: |
        echo "SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path)" >> $GITHUB_ENV
        echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version)" >> $GITHUB_ENV

    - name: Package module
      run: |
        npm install --ignore-scripts
        npm run build -- --target aarch64-apple-darwin
        npm run package
        ls -lR lib build
        
#     - name: Publish prebuilt binaries
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       run: |
#         npm run upload
