name: Build containers
on:
  workflow_dispatch:

jobs:
  # linux:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       libc: [x86, musl]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/${{ github.repository }}-${{ matrix.libc }}:latest
  #         context: arch/${{ matrix.libc }}
  #         push: true

  acorn:
    runs-on: [self-hosted, linux, ${{ matrix.cpu }}]
    strategy:
      matrix:
        cpu: [ARM, ARM64]

    steps:
      - id: cpu
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ matrix.cpu }}

      - name: downcase CPU
        run: |
          echo "CPU=${${{ matrix.cpu }},,}" >>${GITHUB_ENV}
          echo arch is $CPU
          echo cpu is ${{ steps.cpu.outputs.lowercase }}

      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.CR_PAT }}

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     tags: ghcr.io/${{ github.repository }}-${{ steps.cpu.outputs.lowercase }}:latest
      #     context: arch/${{ steps.cpu.outputs.lowercase }}
      #     push: true

  # arm64:
  #   runs-on: [self-hosted, linux, ARM64]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/${{ github.repository }}-arm64:latest
  #         context: arch/arm64
  #         push: true

  # arm:
  #   runs-on: [self-hosted, linux, ARM64]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/${{ github.repository }}-arm:latest
  #         context: arch/arm
  #         push: true
