name: Build containers
on:
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, X64]
    permissions: write-all
    strategy:
      matrix:
        libc: [glibc, musl]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/${{ github.repository }}-${{ matrix.libc }}:latest
        context: arch
        file: arch/Dockerfile.${{ matrix.libc }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
