name: Build containers
on:
  workflow_dispatch:

jobs:
  intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libc: [glibc, musl]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        tags: ghcr.io/${{ github.repository }}-${{ matrix.libc }}:latest
        context: arch/${{ matrix.libc }}
        push: true

  acorn:
    runs-on:
    - self-hosted
    - linux
    - ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        runner: [ARM, ARM64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - id: cpu
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ matrix.runner }}

    - name: Build and Push Docker Image
      run: |
        cd ${{ env.context }}
        docker build . -t ${{ env.tag }}
        docker push ${{ env.tag }}
      env:
        context: arch/${{ steps.cpu.outputs.lowercase }}
        tag: ghcr.io/${{ github.repository }}-${{ steps.cpu.outputs.lowercase }}:latest
