name: Build containers
on:
  workflow_dispatch:

jobs:
  # linux:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       libc: [x86, musl]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/${{ github.repository }}-${{ matrix.libc }}:latest
  #         context: arch/${{ matrix.libc }}
  #         push: true

  acorn:
    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ARM, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Downcase CPU
        run: |
          echo "CPU=$(echo ${{ matrix.runner }} | tr [:upper:] [:lower:])" >> ${GITHUB_ENV}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ github.repository }}-${CPU}:latest
          context: arch/${CPU}
          push: true

  # arm64:
  #   runs-on: [self-hosted, linux, ARM64]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/${{ github.repository }}-arm64:latest
  #         context: arch/arm64
  #         push: true

  # arm:
  #   runs-on: [self-hosted, linux, ARM64]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.CR_PAT }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/${{ github.repository }}-arm:latest
  #         context: arch/arm
  #         push: true
