name: Publish binaries

on:
  workflow_dispatch:
  release:
    types:
      - published
    
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [15]
        os: [macos-latest, windows-latest, ubuntu-18.04]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Fetch ICU data
      if: startsWith(matrix.os,'windows')
      run: |
        mkdir -p lib/v6
        curl -sS https://skia-canvas.s3.us-east-1.amazonaws.com/dependencies/icudtl.dat -o lib/v6/icudtl.dat
    - name: Package module
      run: |
        npm ci
        npm run package
        npm test
    - name: Publish prebuilt binaries
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        npm run publish
