name: Compile binaries
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # libc: [glibc, musl]
        libc: [glibc]

    container:
      image: ${{ format('ghcr.io/{0}-{1}:latest', github.repository, matrix.libc) }}
      # options: --user github

    steps:
    # - name: Use Rust
    #   uses: dtolnay/rust-toolchain@stable
    #   with:
    #     toolchain: stable

    - name: Checkout skia-canvas
      uses: actions/checkout@v4

    - name: Build module
      # run: |
      #   mkdir -p $CARGO_HOME/registry
      #   chown -R github $CARGO_HOME/registry
      #   make optimized
      #   npm test
      run: |
        make optimized
        npm test

  linux-arm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        # libc: [glibc, musl]
        libc: [glibc]

    container:
      image: ${{ format('ghcr.io/{0}-{1}:latest', github.repository, matrix.libc) }}
      # options: --user github

    steps:
    - name: Prepare workspace
      run: |
        rm -rf "$GITHUB_WORKSPACE"
        mkdir -p "$GITHUB_WORKSPACE"

    # - name: Install rust
    #   run: |
    #     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
    #     echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    #     echo CARGO_TERM_COLOR=always >> $GITHUB_ENV

    - name: Checkout skia-canvas
      env:
        SERVER: ${{ github.server_url }}
        REPO: ${{ github.repository }}
        REF: ${{ github.ref_name }}
      run: |
        git clone --depth 1 --branch $REF ${SERVER}/${REPO} .

    - name: Build module
      run: |
        make optimized
        npm test
