name: Compile binaries
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  linux-x86:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/samizdatco/skia-canvas-x86-env:v1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: skia-canvas

    - name: Checkout rust-skia
      id: rust-skia
      run: |
        export TAG=$(awk '/skia-safe/{getline; print}' skia-canvas/Cargo.toml | egrep -o '[0-9\.]+')
        git clone --depth 1 --branch $TAG https://github.com/rust-skia/rust-skia.git
        cd rust-skia
        git submodule update --init --depth 1 skia-bindings/skia
        git submodule update --init --depth 1 skia-bindings/depot_tools

    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Patch build files
      run: perl -0777 -pi.bak -e 's/("textlayout")/$1, "embed-freetype"/' skia-canvas/Cargo.toml

    - name: Build module
      run: |
        cd skia-canvas
        npm ci --ignore-scripts
        npm run build -- --release -p skia-canv

    - name: Package module
      run: |
        cd skia-canvas
        npm test && npm run package

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        cd skia-canvas
        npm run upload
