name: Build containers
on:
  workflow_dispatch:

jobs:
  x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push Docker Image
          uses: docker/build-push-action@v2
          with:
            tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-x86-en:latest
            context: containers/x86
            push: true

  # arm64:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Set up QEMU dependency
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build image
  #     #   if: steps.changed-files-plantcontroller.outputs.any_changed == 'true'
  #       uses: docker/build-push-action@v2
  #       with:
  #         tags: ghcr.io/samizdatco/skia-canvas-x86-env:current
  #         platforms: linux/arm/v7
  #         push: true

  #     #     context: ${{ env.context }}
  #     #     tags: ${{ env.image_name_controller }}
  #     #   env:
  #     #     context: ./controller