name: Find ICU data

on:
  workflow_dispatch:
    
jobs:
  x86-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - windows-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Use Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
          
    - name: Package module
      shell: bash
      run: |
        npm ci --ignore-scripts
        npm run build 
        ICU = $(find . -name icudtl.dat | grep skia-bindings | head -n 1)
        cp $ICU lib/v6
        ls -lR lib
        npm test


#         echo '-------------------------------------------'
#         find . -name icudtl.dat | head -n 1
#         echo ./target/debug/build/skia-bindings-dae28d141e38f8f2/out/skia/icudtl.dat
