name: Test Windows ICU

on:
  workflow_dispatch:
    
jobs:
  x86-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 15

    - name: Use Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable

    - name: Rebuild module
      shell: bash
      run: |
        npm ci --ignore-scripts
        npm run build

    # - name: Use NPM version
    #   shell: bash
    #   run: |
    #     npm ci
    #     npm test

    - name: Test Output
      shell: bash
      run: |
        node testtext.js

    # - name: Test Canvas
    #   shell: bash
    #   run: |
    #     rm package.json package-lock.json
    #     npm init -y
    #     npm i skia-canvas@0.9.25
    #     node testtext.js

    - uses: actions/upload-artifact@v2
      with:
        name: text-rendering-test
        path: abc.png
        retention-days: 5

    - name: Run Tests
      shell: bash
      run: |
        npm test
