name: Check SDK

on:
  workflow_dispatch:
    
jobs:
  apple-silicon:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
          
    steps:    
    - name: Search SDKs
      id: sdk
      run: |
        SDK=$(xcodebuild -showsdks -json | jq -r '.[] | .canonicalName' | grep '^macosx' | tail -n 1)
        echo "::set-output name=macosx::$SDK"
    
    - name: Inspect xcode paths
      run: |
        SDK=steps.find_sdks.outputs.macosx
        echo "SDKROOT=$(xcrun -sdk $SDK --show-sdk-path)"
        echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk $SDK --show-sdk-platform-version)"
