name: Run tests
on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Rebuild & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-18.04
        node:
          - 10
          - 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable

    - name: Setup Python 2 (Window only)
      if: startsWith(matrix.os,'windows')
      uses: actions/setup-python@v2
      with:
        python-version: '2.7.18'
        architecture: 'x64'

    - name: Install LLVM (Window only)
      if: startsWith(matrix.os,'windows')
      run: choco install llvm

    - name: Build module
      run: |
        npm ci --ignore-scripts
        npm run build -- --release

    - name: Run tests
      run: npm test







