name: Run tests
on:
  workflow_dispatch:

jobs:
  run-tests:
    name: Rebuild & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          # - windows-latest
          # - ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Use Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build for Mac
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        python --version
        python3 --version
        npm ci --ignore-scripts
        npm run build -- --release --features metal,window

    - name: Build for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features vulkan,window,skia-safe/embed-freetype,skia-safe/freetype-woff2
    
    - name: Build for Windows
      if: ${{ matrix.os == 'windows-latest' }}
      shell: bash
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features vulkan,window
        
    - name: Run tests
      shell: bash
      run: |
        npm test
        ls -l lib/v6/index.node

