name: Watch for releases
on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish:
    name: Watch for (non-pre) releases
    runs-on: ubuntu-latest

    steps:
    - name: Publish to NPM
      run: |
        echo "WOULD HAVE PUBLISHED!"
